apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: container-1
          image: kavya4041/servicediscovery:01
          ports:
            - containerPort: 8761
        - name: container-2
          image: kavya4041/apigateway:01
          ports:
            - containerPort: 7070
        - name: container-3
          image: kavya4041/studentsapp:01
          ports:
            - containerPort: 8086
        - name: container-4
          image: kavya4041/coursesapp:01
          ports:
            - containerPort: 8087
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
  type: LoadBalancer
